export const defaultPeople = {
  birth_date: "",
  cause_of_death: "",
  education_level: "",
  full_name_vn: "",
  gender: false,
  is_alive: false,
  marital_status: false,
  nationality:"",
  phone_number: "",
  place_of_birth: {
    address_line: "",
    city: "",
    country: "",
    district_or_county: "",
    postal_code: "",
    state_or_province: "",
  },
  place_of_death: {
    address_line: "",
    city: "",
    country: "",
    district_or_county: "",
    postal_code: "",
    state_or_province: "",
  },
  religion: "",
  saint: "",
};
